config/routes.rb
MongoW::Application.routes.draw do
  
  resources :java_dynamic_rows

  resources :validatiions

  resources :challenges

  resources :people

  resources :addresses

  resources :contacts
  
  resources :blogs do
	collection do
		get "blogCreate"
		get "addClass"
		get "add"
		get "after"
	end
 end

  root :to => 'blogs#new'

end

app/models/validatiion.rb
class Validatiion
  include Mongoid::Document
  field :name, :type => String
  field :phone, :type => String
  field :email, :type => String
end

app/controllers/validatiions_controller.rb
class ValidatiionsController < ApplicationController
  # GET /validatiions
  # GET /validatiions.json
  def index
    @validatiions = Validatiion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @validatiions }
    end
  end

  # GET /validatiions/1
  # GET /validatiions/1.json
  def show
    @validatiion = Validatiion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @validatiion }
    end
  end

  # GET /validatiions/new
  # GET /validatiions/new.json
  def new
    @validatiion = Validatiion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @validatiion }
    end
  end

  # GET /validatiions/1/edit
  def edit
    @validatiion = Validatiion.find(params[:id])
  end

  # POST /validatiions
  # POST /validatiions.json
  def create
    @validatiion = Validatiion.new(params[:validatiion])

    respond_to do |format|
      if @validatiion.save
        format.html { redirect_to @validatiion, :notice => 'Validatiion was successfully created.' }
        format.json { render :json => @validatiion, :status => :created, :location => @validatiion }
      else
        format.html { render :action => "new" }
        format.json { render :json => @validatiion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /validatiions/1
  # PUT /validatiions/1.json
  def update
    @validatiion = Validatiion.find(params[:id])

    respond_to do |format|
      if @validatiion.update_attributes(params[:validatiion])
        format.html { redirect_to @validatiion, :notice => 'Validatiion was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @validatiion.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /validatiions/1
  # DELETE /validatiions/1.json
  def destroy
    @validatiion = Validatiion.find(params[:id])
    @validatiion.destroy

    respond_to do |format|
      format.html { redirect_to validatiions_url }
      format.json { head :ok }
    end
  end
end

app/helpers/validatiions_helper.rb
module ValidatiionsHelper
end

app/views/validatiions/_form.html.erb
<%= form_for :validatiion, :url => {:controller=> "validatiions",:action => "create"},:html=>{:multipart => true, :name => "newproject_form", :onSubmit => "return validate_form_fields(this);"} do |f| -%>  
  <% if @validatiion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@validatiion.errors.count, "error") %> prohibited this validatiion from being saved:</h2>

      <ul>
      <% @validatiion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
	<div id="name"></div>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
	<div id="phone"></div>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
	<div id="email"></div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<script language="javascript" type="text/javascript">
	function validate_form_fields()
	{
		alert("hiiiiiiiiiii");
		if(document.newproject_form.validatiion_name.value=="")
		{
			alert("hi");
			document.getElementById("name").innerHTML="<font color=\"#FF0000\">Please enter your Name</font>";
			document.newproject_form.validatiion_name.focus();
			alert("hi");
			return false;
		}
		
		if(document.newproject_form.validatiion_phone.value=="")
		{
			document.getElementById("phone").innerHTML="<font color=\"#FF0000\">Please enter your Contact No</font>";
			document.newproject_form.validatiion_phone.focus();
			return false;
		}
		
		if(document.newproject_form.validatiion_email.value=="")
		{
			document.getElementById("email").innerHTML="<font color=\"#FF0000\">Please enter your Comments</font>";
			document.newproject_form.validatiion_email.focus();
			return false;
		}
	}
</script> 

app/views/validatiions/edit.html.erb
<h1>Editing validatiion</h1>

<%= render 'form' %>

<%= link_to 'Show', @validatiion %> |
<%= link_to 'Back', validatiions_path %>

app/views/validatiions/index.html.erb
<h1>Listing validatiions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @validatiions.each do |validatiion| %>
  <tr>
    <td><%= validatiion.name %></td>
    <td><%= validatiion.phone %></td>
    <td><%= validatiion.email %></td>
    <td><%= link_to 'Show', validatiion %></td>
    <td><%= link_to 'Edit', edit_validatiion_path(validatiion) %></td>
    <td><%= link_to 'Destroy', validatiion, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Validatiion', new_validatiion_path %>

app/views/validatiions/new.html.erb
<h1>New validatiion</h1>

<%= render 'form' %>

<%= link_to 'Back', validatiions_path %>

app/views/validatiions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @validatiion.name %>
</p>

<p>
  <b>Phone:</b>
  <%= @validatiion.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @validatiion.email %>
</p>


<%= link_to 'Edit', edit_validatiion_path(@validatiion) %> |
<%= link_to 'Back', validatiions_path %>