config/routes.rb
MongoW::Application.routes.draw do
  
  resources :java_dynamic_rows

  resources :validatiions

  resources :challenges

  resources :people

  resources :addresses

  resources :contacts
  
  resources :blogs do
	collection do
		get "blogCreate"
		get "addClass"
		get "add"
		get "after"
	end
 end

  root :to => 'blogs#new'

end

app/models/address.rb
class Address
  include Mongoid::Document
  field :email, :type => String
  field :country, :type => String
  
  embedded_in :contact, :inverse_of => :address
end

app/models/blog.rb
class Blog
  include Mongoid::Document
  field :name, :type => String
  field :body, :type => String
end

app/models/browser.rb
class Browser
  include Mongoid::Document
  field :version, :type => Integer
  scope :recent, where(:version.gt => 3)
end

app/models/challenge.rb
class Challenge
  include Mongoid::Document
  #accepts_nested_attributes_for :tasks
  #attr_accessible :name, :tasks
  field :name, :type => String
  embeds_many :tasks
end

app/models/contact.rb
class Contact
  include Mongoid::Document
  field :name, :type => String
  
  embeds_many :addresses
end

app/models/convas.rb
class Convas
  include Mongoid::Document
  field :name, :type => String
  
  embeds_many :shapes
end

app/models/detail.rb
class Detail
  include Mongoid::Document
  field :email, :type => String
  
end

app/models/firefox.rb
class Firefox
  include Mongoid::Document
  
end

app/models/java_dynamic_row.rb
class JavaDynamicRow
  include Mongoid::Document
  field :name, :type => String
end

app/models/person.rb
class Person < Detail
  include Mongoid::Document
  field :name, :type => String
  
end

app/models/task.rb
class Task
  include Mongoid::Document
  field :score
  field :score_by
  embedded_in :challenge, :inverse_of => :tasks
end

app/models/validatiion.rb
class Validatiion
  include Mongoid::Document
  field :name, :type => String
  field :phone, :type => String
  field :email, :type => String
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # GET /blogs
  # GET /blogs.json
  
  def addClass
  
  end
  
  def index
    @blogs = Blog.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
	 @blogs = Blog.all
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])
  end

  # POST /blogs
  # POST /blogs.json
  def create
   @blog = Blog.new(params[:blog])
   @blog.save
   redirect_to :action => "new"
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, :notice => 'Blog was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @blog.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    redirect_to :action => "new"
  end
  
  def blogCreate
	raise "aaaa"
  end
end

app/controllers/java_dynamic_rows_controller.rb
class JavaDynamicRowsController < ApplicationController
  # GET /java_dynamic_rows
  # GET /java_dynamic_rows.json
  def index
    @java_dynamic_rows = JavaDynamicRow.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @java_dynamic_rows }
    end
  end

  # GET /java_dynamic_rows/1
  # GET /java_dynamic_rows/1.json
  def show
    @java_dynamic_row = JavaDynamicRow.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @java_dynamic_row }
    end
  end

  # GET /java_dynamic_rows/new
  # GET /java_dynamic_rows/new.json
  def new
    @java_dynamic_row = JavaDynamicRow.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @java_dynamic_row }
    end
  end

  # GET /java_dynamic_rows/1/edit
  def edit
    @java_dynamic_row = JavaDynamicRow.find(params[:id])
  end

  # POST /java_dynamic_rows
  # POST /java_dynamic_rows.json
  def create
    @java_dynamic_row = JavaDynamicRow.new(params[:java_dynamic_row])

    respond_to do |format|
      if @java_dynamic_row.save
        format.html { redirect_to @java_dynamic_row, :notice => 'Java dynamic row was successfully created.' }
        format.json { render :json => @java_dynamic_row, :status => :created, :location => @java_dynamic_row }
      else
        format.html { render :action => "new" }
        format.json { render :json => @java_dynamic_row.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /java_dynamic_rows/1
  # PUT /java_dynamic_rows/1.json
  def update
    @java_dynamic_row = JavaDynamicRow.find(params[:id])

    respond_to do |format|
      if @java_dynamic_row.update_attributes(params[:java_dynamic_row])
        format.html { redirect_to @java_dynamic_row, :notice => 'Java dynamic row was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @java_dynamic_row.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /java_dynamic_rows/1
  # DELETE /java_dynamic_rows/1.json
  def destroy
    @java_dynamic_row = JavaDynamicRow.find(params[:id])
    @java_dynamic_row.destroy

    respond_to do |format|
      format.html { redirect_to java_dynamic_rows_url }
      format.json { head :ok }
    end
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, :notice => 'Person was successfully created.' }
        format.json { render :json => @person, :status => :created, :location => @person }
      else
        format.html { render :action => "new" }
        format.json { render :json => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, :notice => 'Person was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @person.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :ok }
    end
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/java_dynamic_rows_helper.rb
module JavaDynamicRowsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/validatiions_helper.rb
module ValidatiionsHelper
end

app/views/java_dynamic_rows/_form.html.erb
<%= form_for(@java_dynamic_row) do |f| %>
  <% if @java_dynamic_row.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@java_dynamic_row.errors.count, "error") %> prohibited this java_dynamic_row from being saved:</h2>

      <ul>
      <% @java_dynamic_row.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div id="hidden" style="display:none;">
    <%= f.label :name %><br />
    <%= f.text_field :name %><input type="button" value="Remove" id="re">
  </div>
  
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %><input type="button" value="Add" id="ad">
  </div>	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<script type="text/javascript">
	$('#ad').click(function() {
		//$("hidden").add();
		$("#hidden").show("slow");
	});
	
	$('#re').click(function() {
		$("#hidden").hide("fast"); 
	});
</script>








<div id="p_scents">
    <p>
        <label for="p_scnts"><input type="text" id="p_scnt" size="20" name="p_scnt" value="" placeholder="Input Value" /></label><a href="#" id="addScnt">Add Another Input Box</a>
    </p>
</div>


<script type="text/javascript">
	$(function() {
        var scntDiv = $('#p_scents');
        var i = $('#p_scents p').size() + 1;
		
		        $('#addScnt').live('click', function() {
                $('<p><label for="p_scnts"><input type="text" id="p_scnt" size="20" name="p_scnt_' + i +'" value="" placeholder="Input Value" /></label> <a href="#" id="remScnt">Remove</a></p>').appendTo(scntDiv);
                i++;
                return false;
        });

        $('#remScnt').live('click', function() {
                if( i > 2 ) {
                        $(this).parents('p').remove();
                        i--;
                }
                return false;
        });
});
</script>

app/views/java_dynamic_rows/edit.html.erb
<h1>Editing java_dynamic_row</h1>

<%= render 'form' %>

<%= link_to 'Show', @java_dynamic_row %> |
<%= link_to 'Back', java_dynamic_rows_path %>

app/views/java_dynamic_rows/index.html.erb
<h1>Listing java_dynamic_rows</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @java_dynamic_rows.each do |java_dynamic_row| %>
  <tr>
    <td><%= java_dynamic_row.name %></td>
    <td><%= link_to 'Show', java_dynamic_row %></td>
    <td><%= link_to 'Edit', edit_java_dynamic_row_path(java_dynamic_row) %></td>
    <td><%= link_to 'Destroy', java_dynamic_row, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Java dynamic row', new_java_dynamic_row_path %>

app/views/java_dynamic_rows/new.html.erb
<h1>New java_dynamic_row</h1>

<%= render 'form' %>

<%= link_to 'Back', java_dynamic_rows_path %>

app/views/java_dynamic_rows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @java_dynamic_row.name %>
</p>


<%= link_to 'Edit', edit_java_dynamic_row_path(@java_dynamic_row) %> |
<%= link_to 'Back', java_dynamic_rows_path %>